### ISSUE TITLE
Time Limit Issue

### ISSUE THREAD

**Issue by tanimahossain** [lightoj-dev/bugs-and-features#88]
I am not 100% sure if it is a bug. But even if it isn't, I want to make sure if it's intentional or not. As all of the problems on LightOJ are rejudged, some verdicts are changed. Previously accepted codes are getting Wrong answers or Time Limit Exceeded. I can get the wrong answer part that the dataset might be weak before. But when it comes to the Time limit part I have checked some problems which I have solved in **vjudge.net**. Where I have conveniently used some approaches which got accepted within the time limit. But now it is getting a TLE. Then I noticed that the time limit of those problems is reduced. For Example-
Josephus Problem LightOJ - 1179, Previous verdict - Accepted, Time - 1849ms
Current Verdict - Time Limit Exceed, Current Time Limit - 1000ms
![image](https://user-images.githubusercontent.com/56477789/115857653-c0443800-a44f-11eb-8ddd-51768d5bb5fa.png)

Jane and the Frost Giants LightOJ - 1175, Previous verdict - Accepted, Time - 1740ms
Current Verdict - Time Limit Exceed, Current Time Limit - 1000ms
![image](https://user-images.githubusercontent.com/56477789/115857610-b28eb280-a44f-11eb-964d-5e9ad27c50bf.png)

If these are intentional then I have no say here. But as many of us directly solve in the OJ and have no idea if the problem is TLE because the time limit is reduced and we should try to solve it in a new approach or it was TLE before the upgrade because we didn't get an optimized idea. It will be really helpful if the problems with timelimit changes are marked or published in some kind of way. In short, if there's any way that we can know this change.
Thank you.

**Comment by jan876** [comment]
Hi,

Really appreciate you reporting these issues. Because of the migration to the new systems, we upgraded our judge servers with better configurations. As a result, we reduced time limits for some of the problems.

For WA, as you mentioned, we have gotten some modified user datasets which we uploaded as part of the migration.

For TLE, I would suggest creating multiple tickets, for different problems and submit your submission id. We will surely take a look and might increase limits if necessary.

Please take a look at the following ticket as an example: https://github.com/lightoj-dev/bugs-and-features/issues/15
